<!doctype html>
<html lang="en">

<style>
    body {
        padding: 0;
        margin: 0;
        text-align: center;
    }

    * {
        text-align: center;
    }

    .title {
        font-size: 70px;
        padding: 0;
    }

    .sub-title {
        font-size: 20px;
        margin-top: -8%;
    }

    .text-container {
        position: absolute;
        top: 20%;
        left: 50%;
        transform: translate(-50%);
    }

    .form-container {
        position: absolute;
        top: 45%;
        left: 50%;
        transform: translate(-50%);
        width: 30%;
    }

    .btn {
        margin-top: 10%;
        width:100%
    }

    .alert {
        position: absolute;
        left: 50%;
        transform: translate(-50%,-10%);
        width: 125%;
        visibility: hidden;
    }
</style>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href='http://fonts.googleapis.com/css?family=Oleo+Script' rel='stylesheet' type='/css/styles.css'>
    <title>Login</title>
</head>
<body>

<div class="text-container">
    <p class="title"><b>Welcome!</b></p>
    <p class="sub-title">Login to continue</p>
</div>


<div class="form-container">
    <div class="alert alert-danger" id="err" role="alert">
        User credentials provided is incorrect.
    </div>
    <form  method="POST">
        <div class="form-group">
            <input type="text" class="form-control" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" name="password" placeholder="Password">
        </div>

        <button type="submit" name="loginbutton" class="btn btn-primary">Login</button>
    </form>
</div>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>